//
//  Eof
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Eof.h"

@implementation Eof

- (NSMutableString*) toString{
	return @"Eof";
}
- (id) init{
	self = [super init];
	return self;
}

@end
