//
//  main.m
//  app_delegate_class
//
//  Source generated by Haxe Objective-C target
//

#import ".h"

@implementation Eof

- (NSMutableString*) toString{
	return @"Eof";
}
- (id) new{
	self = [super init];
	return self;
}

@end
