//
//  Lib
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Lib.h"

@implementation Lib

+ (void) print:(id)v{
	printf ( [[v description] cStringUsingEncoding:NSStringEncodingConversionAllowLossy] );
}
+ (void) println:(id)v{
	[LibFA_TAnon_ print:v];
	printf ( "\n" );
}

@end
