//
//  Lib
//  Tests
//
//  Source generated by Haxe Objective-C target
//


#import <CoreLocation/CoreLocation.h>

#import "../objc/Lib.h"

@interface Lib : HXObject

+ (void) log:(id)v;
+ (void) print:(id)v;
+ (void) println:(id)v;
+ (CLLocation*) location;

@end

