//
//  BytesInput
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../../Array.h"
#import "../../haxe/io/Eof.h"
#import "../../haxe/io/Bytes.h"
#import "../../haxe/io/Error.h"
#import "../../haxe/io/Input.h"

@interface BytesInput : Input 

@property (nonatomic, strong) NSMutableArray *b;
@property (nonatomic) int pos;
@property (nonatomic) int len;
- (int) readByte;
- (int) readBytes:(Bytes*)buf pos:(int)pos len:(int)len;
- (id) init:(Bytes*)b pos:(int)pos len:(int)len;

@end

