//
//  FastList
//  Tests
//
//  Source generated by Haxe Objective-C target
//



#import "FastList.h"

@interface FastCell : NSObject

@property (nonatomic) id elt;
@property (nonatomic, strong) FastCell *next;
- (id) init:(id)elt next:(FastCell*)next;

@end



#import "FastList.h"

@interface FastList : NSObject

@property (nonatomic, strong) FastCell *head;
- (id) init;

@end

