//
//  Log
//  Tests
//
//  Source generated by Haxe Objective-C target
//




@interface Log : NSObject

// Defining a dynamic method
+ (void) trace:(id)v infos:(id)infos;
@property (nonatomic,copy) void(^block_trace)(id, id);
// Defining a dynamic method
+ (void) clear;
@property (nonatomic,copy) void(^block_clear)();

@end

