//
//  Log
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Log.h"

@implementation Log

+ (void) trace:(id)v infos:(id)infos{
	if (infos==nil) infos=nil;
	NSLog (@"%@:%@: %@", [infos objectForKey:@"fileName"], [infos objectForKey:@"lineNumber"], v);
}
+ (void) clear{
}

@end
