//
//  Log
//  Tests
//
//  Source generated by Haxe Objective-C target
//




@interface Log : NSObject

@property (nonatomic,copy) (void) trace:(id)v infos:(id)infos;
@property (nonatomic,copy) (void) clear;

@end

