//
//  Timer
//  Tests
//
//  Source generated by Haxe Objective-C target
//


#import <Foundation/Foundation.h>

#import "Timer.h"
#import "Array.h"
#import "T.h"
#import "Log.h"
#import "Sys.h"

@interface Timer : NSObject

+ (Timer*) delay:(SEL)f time_ms:(int)time_ms;
+ (id) measure:(SEL)f pos:(id)pos;
+ (float) stamp;
@property (nonatomic, strong) NSTimer *nstimer;
@property (nonatomic) int _id;
- (void) stop;
// Defining a dynamic method
- (void) run;
@property (nonatomic,copy) void(^property_run)();
- (id) init:(int)time_ms;

@end

