//
//  Int64
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../haxe/Int64.h"
#import "../String.h"

@interface Int64 : HXObject

+ (int) toInt:(Int64*)x;
+ (int) getLow:(Int64*)x;
+ (int) getHigh:(Int64*)x;
+ (Int64*) sub:(Int64*)a b:(Int64*)b;
+ (id) divMod:(Int64*)modulus divisor:(Int64*)divisor;
+ (int) uicompare:(int)a b:(int)b;
@property (nonatomic) int high;
@property (nonatomic) int low;
- (NSMutableString*) toString;
- (id) init:(int)high low:(int)low;

@end

