//
//  Resource
//  Test
//
//  Source generated by Haxe Objective-C target
//


#import <Foundation/Foundation.h>

#import "../Array.h"
#import "../haxe/Resource.h"
#import "../String.h"
#import "../haxe/io/Bytes.h"

@interface Resource : HXObject

+ (NSMutableDictionary*) __plist__:(NSMutableDictionary*)val;
+ (NSMutableArray*) listNames;
+ (NSMutableString*) getString:(NSMutableString*)name;
+ (Bytes*) getBytes:(NSMutableString*)name;

@end

