//
//  List
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "Array.h"

@interface List : HXObject

@property (nonatomic, strong) NSMutableArray *h;
@property (nonatomic, strong) NSMutableArray *q;
@property (nonatomic) int length;
- (void) add:(id)item;
- (void) push:(id)item;
- (id) first;
- (id) pop;
- (BOOL) isEmpty;
- (id) iterator;
- (id) init;

@end

