//
//  FileOutput
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "FileOutput.h"

@implementation FileOutput

+ (id) __meta__:(id)val {
	static id _val;
	if (val == nil) { if (_val == nil) _val = struct {
obj:struct {
core_api:nil
} structName
} structName; }
	else { if (_val != nil) _val = val; }
	return _val;
}
@synthesize __f;
- (void) writeByte:(int)c{
}
- (int) writeBytes:(Bytes*)s p:(int)p l:(int)l{
	return 0;
}
- (void) flush{
}
- (void) close{
	[super close];
}
- (void) seek:(int)p pos:(FileSeek*)pos{
}
- (int) tell{
	return 0;
}
- (id) init:(id)f{
	self = [super init];
	self.__f = f;
	return self;
}

@end
