//
//  Array
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Array.h"

@implementation NSMutableArray ( Array )

// Getters/setters for property length
static int length__;
- (int) length { return length__; }
- (void) setLength:(int)val { length__ = val; }

- (NSMutableArray*) concat:(NSMutableArray*)a{
	return FDynamic[self arrayByAddingObjectsFromArray:a];
}
- (NSMutableArray*) copy{
	return FDynamic[NSMutableArray arrayWithArray:self];
}
- (id) iterator{
	return struct {
	a:self; p:0; hasNext:^- (BOOL) {
		return self.p < self.a length;
	}; next:^- (id) {
		id i = [self.a objectAtIndex:self.p];
		self.p += 1;
		return i;
	}
	} structName;
}
- (void) insert:(int)pos x:(id)x{
	[self insertObject:x atIndex:pos];
}
- (NSMutableString*) join:(NSMutableString*)sep{
	return FDynamic[self componentsJoinedByString:sep];
}
- (NSMutableString*) toString{
	return [(NSMutableString*)@"[" stringByAppendingString: ([FDynamic[self componentsJoinedByString:(NSMutableString*)@","] stringByAppendingString:(NSMutableString*)@"]"])];
}
- (id) pop{
	if (self.length == 0) return nil;
	id theLastObject = FDynamic[self lastObject];
	FDynamic[self removeLastObject];
	return theLastObject;
}
- (int) push:(id)x{
	FDynamic[self addObject:x];
	return FDynamic[self count];
}
- (void) unshift:(id)x{
	[self insertObject:x atIndex:0];
}
- (BOOL) remove:(id)x{
	BOOL containsObject = FDynamic[self containsObject:x];
	if (containsObject) FDynamic[self removeObject:x];
	return containsObject;
}
- (void) reverse{
	id reverseArray = FAnon[FDynamic[self reverseObjectEnumerator] allObjects];
}
- (id) shift{
	if (FDynamic[self count] > 0) {
		id obj = FDynamic[self objectAtIndex:0];
		FDynamic[self removeObjectAtIndex:0];
		return obj;
	}
	return nil;
}
- (NSMutableArray*) slice:(int)pos end:(int)end{
	// Simulated optional arguments
	if (end == nil) end = nil;
	
	return [self splice:pos len:end - pos];
}
- (void) sort:(SEL)f{
}
- (NSMutableArray*) splice:(int)pos len:(int)len{
	
	NSMutableArray *newArray = (NSMutableArray*)FDynamic[self subarrayWithRange:NSMakeRange (pos,len)];
	FDynamic[self removeObjectsInArray:newArray];
	return FDynamic[NSMutableArray arrayWithArray:newArray];
}
- (id) init{
	self = [super init];
	return self;
}

@end
