//
//  IntHash
//  Tests
//
//  Source generated by Haxe Objective-C target
//



#import "Array.h"

@interface NSMutableDictionary ( IntHash )

- (void) set:(int)key value:(id)value;
- (id) get:(int)key;
- (BOOL) exists:(int)key;
- (BOOL) remove:(int)key;
- (id_anon*) keys;
- (id_anon*) iterator;
- (NSMutableString*) toString;
- (id) init;

@end

