//
//  IntHash
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "IntHash.h"

@implementation NSMutableDictionary ( IntHash )

+ (id) __meta__:(id)val {
	static id _val;
	if (val == nil) { if (_val == nil) _val = struct {
obj:struct {
:core_api:nil
} structName
} structName; }
	else { if (_val != nil) _val = val; }
	return _val;
}
- (void) set:(int)key value:(id)value{
	[self setObject:value forKey:[NSString stringWithFormat:@"%i",key]];
}
- (id) get:(int)key{
	return [self objectForKey:[NSString stringWithFormat:@"%i",key]];
}
- (BOOL) exists:(int)key{
	return [self objectForKey:[NSString stringWithFormat:@"%i",key]] != nil;
}
- (BOOL) remove:(int)key{
	if ([self exists:key]) {
		[self removeObjectForKey:[NSString stringWithFormat:@"%i",key]];
		return YES;
	}
	return NO;
}
- (id) keys{
	
	NSMutableArray *a = (NSMutableArray*)[self allKeys];
	return [a iterator];
}
- (id) iterator{
	
	NSMutableArray *a = (NSMutableArray*)[self allValues];
	return [a iterator];
}
- (NSMutableString*) toString{
	return [self description];
}
- (id) init{
	self = [super init];
	return self;
}

@end
