//
//  IntHash
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "IntHash.h"

@implementation NSMutableDictionary ( IntHash )

- (void) set:(int)key value:(id)value{
	[self setObject:value forKey:[NSString stringWithFormat:@"%i",key]];
}
- (id) get:(int)key{
	return [self objectForKey:[NSString stringWithFormat:@"%i",key]];
}
- (BOOL) exists:(int)key{
	return [self objectForKey:[NSString stringWithFormat:@"%i",key]] != nil;
}
- (BOOL) remove:(int)key{
	if ([self exists:key]) {
		[self removeObjectForKey:[NSString stringWithFormat:@"%i",key]];
		return YES;
	}
	return NO;
}
- (id_anon*) keys{
	
	NSMutableArray *a = [self allKeys];
	return [a iterator];
}
- (id_anon*) iterator{
	
	NSMutableArray *a = [self allValues];
	return [a iterator];
}
- (NSMutableString*) toString{
	return [self description];
}
- (id) init{
	self = [super init];
	return self;
}

@end
