//
//  IntIterator
//  Tests
//
//  Source generated by Haxe Objective-C target
//




@interface IntIterator : NSObject

@property (nonatomic) int min;
@property (nonatomic) int max;
- (BOOL) hasNext;
- (int) next;
- (id) init:(int)min max:(int)max;

@end

