//
//  StringBuf
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "StringBuf.h"

@implementation StringBuf

@synthesize b;
- (id) init{
	self = [super init];
	self.b = (NSMutableString*)@"";
	return self;
}

@end
