//
//  Sys
//  Tests
//
//  Source generated by Haxe Objective-C target
//



#import "Sys.h"
#import "haxe/io/Input.h"
#import "sys/io/FileInput.h"
#import "haxe/io/Output.h"
#import "sys/io/FileOutput.h"
#import "Array.h"
#import "String.h"
#import "Hash.h"

@interface Sys : NSObject

+ (void) print:(id)v;
+ (void) println:(id)v;
+ (Input*) stdin;
+ (Output*) stdout;
+ (Output*) stderr;
+ (int) getChar:(BOOL)echo;
+ (NSMutableArray*) args;
+ (NSMutableString*) getEnv:(NSMutableString*)s;
+ (void) putEnv:(NSMutableString*)s v:(NSMutableString*)v;
+ (void) sleep:(float)seconds;
+ (BOOL) setTimeLocale:(NSMutableString*)loc;
+ (NSMutableString*) getCwd;
+ (void) setCwd:(NSMutableString*)s;
+ (NSMutableString*) systemName;
+ (NSMutableString*) escapeArgument:(NSMutableString*)arg;
+ (int) command:(NSMutableString*)cmd args:(NSMutableArray*)args;
+ (void) exit:(int)code;
+ (float) time;
+ (float) cpuTime;
+ (NSMutableString*) executablePath;
+ (Hash*) environment;

@end

