//
//  Tests
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Tests.h"

@implementation Tests

+ (NSMutableString*) staticVar1:(NSMutableString*)val {
	static NSMutableString *_val;
	if (val == nil) { if (_val == nil) _val = @"abcd"; }
	else { if (_val != nil) _val = val; }
	return _val;
}
+ (int) staticVar2:(int)val {
	static int _val;
	if (val == nil) { if (_val == nil) _val = 5; }
	else { if (_val != nil) _val = val; }
	return _val;
}
+ (int) staticVar3:(int)val {
	static int _val;
	if (val == nil) { if (_val == nil) _val = 5; }
	else { if (_val != nil) _val = val; }
	return _val;
}

@synthesize interfaceVar1;
@synthesize interfaceVar2;

@synthesize d1;
@synthesize d2;
@synthesize s;
- (void) testVariables{
	
	NSMutableArray *a = [[NSMutableArray alloc] init];
	int b = 5;
	float c = 5.0;
	
	NSMutableString *d = @"xyz";
	BOOL e = YES;
	int f;
	int g = (int)5.3;
	id g1 = (id)6.3;
	id g2 = (id)a;
	int xy = a.length;
	[a push:@"6"];
	if (a.length > 3) f = 3
	else f = a.length;
	f = ( (a.length > 3) ? 3 : a.length);
	int x = [[[Tests alloc] init] add:1 b:1];
	[LibFA_TAnon_ print:@"print print and print again"];
	[LibFA_TAnon_ println:@"print print and print again"];
}
- (void) testingFor{
	
	NSMutableArray *aa = [[NSMutableArray alloc] initWithObjects:[NSNumber numberWithInt:1], [NSNumber numberWithInt:2], [NSNumber numberWithInt:3], [NSNumber numberWithInt:4], [NSNumber numberWithInt:5], nil]];
	{
		int _g = 0;
		while (_g < 5) {
			int i = _g++;
			[aa push:i];
		}
	}
	{
		int _g1 = 0; int _g = aa.length;
		while (_g1 < _g) {
			int i = _g1++;
			[aa push:i];
		}
	}
	{
		int _g = 0;
		while (_g < aa.length) {
			int i = [aa objectAtIndex:_g];
			++_g;
			[aa push:i];
		}
	}
}
- (void) testWhile{
	int aa = 5;
	do {
		[LogFA_TAnon_ trace:@"do something" infos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Tests.hx",@"88",@"Tests",@"testWhile",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
		aa++;
	}while (aa < 10);
	while (aa > 0) aa--;
}
- (void) testTry{
	@try {
		int a = 3;
	}
	@catch (NSException *e) {
		[LogFA_TAnon_ trace:@"error" infos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Tests.hx",@"105",@"Tests",@"testTry",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	}
}
- (void) testSwitch{
	BOOL _g = YES;
	switch (_g){
		case YES:{
			{
				int x = 0;
			}}break;
		case NO:{
			{
				int y = 0;
			}}break;
	}
}
- (void) testArray{
	
	NSMutableArray *as = [[NSMutableArray alloc] init];
	
	NSMutableArray *aa = [[NSMutableArray alloc] initWithObjects:[NSNumber numberWithFloat:1.0], [NSNumber numberWithInt:2], [NSNumber numberWithInt:3], [NSNumber numberWithInt:4], [NSNumber numberWithInt:5], nil]];
	float aaa = [aa objectAtIndex:2];
	[aa objectAtIndex:3];
	
	NSMutableArray *concatArray = [as concat:[[NSMutableArray alloc] initWithObjects:@"5", @"6", @"7", nil]]];
	concatArray = [as copy];
	[concatArray insert:2 x:@"2"];
	
	id_anon *iter = [as iterator];
	
	NSMutableString *s = [concatArray join:@", "];
	
	NSMutableString *item = [as pop];
	[as push:@"454"];
	BOOL bool = [as remove:@"5"];
	[as reverse];
	item = [as shift];
	
	NSMutableArray *sliceArray = [as slice:1 end:3];
	[as sort:^(int):(NSMutableString*)a b:(NSMutableString*)b{
		return 0;
	}];
	sliceArray = [as splice:2 len:2];
	s = [as toString];
	[as unshift:@"44"];
}
- (void) testDate{
	
	NSDate *d = [[NSDate alloc] init:2012 month:11 day:13 hour:19 min:30 sec:0];
	int _int = [d  getDate];
	_int = [d  getDay];
	_int = [d  getFullYear];
	_int = [d  getHours];
	_int = [d  getMinutes];
	_int = [d  getMonth];
	_int = [d  getSeconds];
	float _float = [d  getTime];
	
	NSMutableString *str = [d  toString];
	
	NSDate *d2 = [NSDateFA_TAnon_  fromString:@"2012-12-12 06:40:00"];
	d2 = [NSDateFA_TAnon_ fromTime:120000];
	d2 = [NSDateFA_TAnon_ now];
	int x = [DateToolsFA_TAnon_ getMonthDays:d2];
	_float = [DateToolsFA_TAnon_ days:5];
	
	NSDate *d3 = [DateToolsFA_TAnon_ delta:d t:1000.0];
	str = [DateToolsFA_TAnon_ format:d f:@"HH:mm"];
	_int = [DateToolsFA_TAnon_ getMonthDays:d];
	_float = [DateToolsFA_TAnon_ hours:1000];
	_float = [DateToolsFA_TAnon_ make:struct {
	seconds:0; ms:(float)110; minutes:6; hours:8; days:5
	} structName];
	_float = [DateToolsFA_TAnon_ minutes:56];
	
	id_anon *obj = [DateToolsFA_TAnon_ parse:45546];
	_float = [DateToolsFA_TAnon_ seconds:1000];
}
- (int) enumToInt:(Tests*)c{
	[self.testEnum:TestsEnumExternFA_TAnon_ -GFA2-ExternEnumValue1];
	return ((int)($this:(snd ctx.path)) 
	var $e2 : enum =  (c)
	switch ( $e2.index ) {
		
		case 0:
		{
			__r__ = 16711680}break
		case 1:
		{
			__r__ = 65280}break
		case 2:
		{
			__r__ = 255}break
		case 3:
		
		var MATCH c_eGrey_0 : int = $e2.params[0]{
			__r__ = ((c_eGrey_0 << 16 | c_eGrey_0 << 8) | c_eGrey_0)}break
		case 4:
		
		var MATCH c_eRgb_2 : int = $e2.params[2], MATCH c_eRgb_1 : int = $e2.params[1], MATCH c_eRgb_0 : int = $e2.params[0]{
			__r__ = ((c_eRgb_0 << 16 | c_eRgb_1 << 8) | c_eRgb_2)}break
		case 5:
		
		var MATCH c_eAlpha_1 : Tests = $e2.params[1], MATCH c_eAlpha_0 : int = $e2.params[0]{
			__r__ = (c_eAlpha_0 << 24 | ([self.enumToInt:c_eAlpha_1] & 16777215))}break
	}
	return __r__{
		
		int* __r__}
	}(self));
}
- (void) testEnum:(Object*)v{
	int i = ((int)($this:(snd ctx.path)) 
	var $e2 : enum =  (v)
	switch ( $e2.index ) {
		
		case 0:
		{
			__r__ = 5}break
		case 1:
		{
			__r__ = 6}break
		case 2:
		{
			__r__ = 7}break
	}
	return __r__{
		
		int* __r__}
	}(self));
	
	Tests *red = Color2FA_TAnon_ -GFA2-Red2;
	int j = ((int)($this:(snd ctx.path)) 
	var $e4 : enum =  (red)
	switch ( $e4.index ) {
		
		case 0:
		{
			__r__3 = 5}break
		case 1:
		{
			__r__3 = 6}break
		case 2:
		{
			__r__3 = 7}break
	}
	return __r__3{
		
		int* __r__3}
	}(self));
}
- (void) testEReg{
	
	EReg *ereg = [[EReg alloc] init:@"ytrytrevev76" opt:@"099"];
	
	NSMutableString *s = [ereg customReplace:@"s" f:^(NSMutableString*):(EReg*)e{
		return @"ss";
	}];
	BOOL b = [ereg match:@"s"];
	s = [ereg matched:5];
	s = [ereg matchedLeft];
	
	id_anon *o = [ereg matchedPos];
	s = [ereg matchedRight];
	s = [ereg replace:@"s" by:@"by"];
	
	NSMutableArray *arr = [ereg split:@","];
}
- (void) testHash{
	
	Hash *h = [[Hash alloc] init];
	[h set:@"key" value:@"value"];
	[h get:@"key"];
	[h remove:@"key"];
	BOOL b = [h exists:@"key"];
	
	id_anon *arr = [h keys];
	
	id_anon *iter = [h iterator];
	
	NSMutableString *str = [h toString];
	
	IntHash *hi = [[IntHash alloc] init];
	[hi set:0 value:@"value"];
	[hi get:0];
	[hi remove:0];
	BOOL bi = [hi exists:0];
	
	id_anon *arri = [hi keys];
	
	id_anon *iteri = [hi iterator];
	
	NSMutableString *stri = [hi toString];
}
- (void) testLambda{
	
	NSMutableArray *a = [LambdaFA_TAnon_ array:[[NSMutableArray alloc] initWithObjects:[NSNumber numberWithInt:0], [NSNumber numberWithInt:1], [NSNumber numberWithInt:2], [NSNumber numberWithInt:3], nil]]];
	
	List *l = [LambdaFA_TAnon_ concat:[[NSMutableArray alloc] initWithObjects:[NSNumber numberWithInt:0], [NSNumber numberWithInt:1], [NSNumber numberWithInt:2], [NSNumber numberWithInt:3], nil]] b:[[NSMutableArray alloc] initWithObjects:[NSNumber numberWithInt:4], [NSNumber numberWithInt:5], nil]]];
}
- (void) testList{
	
	List *l = [[List alloc] init];
	[l add:2];
	[l push:18];
	
	List *l2 = [l filter:^(BOOL):(int)i{
		return i > 5;
	}];
	int item = [l first];
	BOOL empty = [l isEmpty];
	
	id_anon *iter = [l iterator];
	
	NSMutableString *s = [l join:@", "];
	s = [l toString];
	item = [l last];
	item = [l pop];
	BOOL r = [l remove:5];
	[LogFA_TAnon_ trace:l length infos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Tests.hx",@"285",@"Tests",@"testList",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[l clear];
	[LogFA_TAnon_ trace:l length infos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Tests.hx",@"287",@"Tests",@"testList",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	List *newList = [l map:^(NSMutableString*):(int)i{
		return [StdFA_TAnon_ string:i];
	}];
	
	FastList *fl = [[FastList alloc] init];
	fl.head = [[FastCell alloc] init:8 next:fl head];
}
- (void) testMath{
	float pi = FA_TAnon_ M_PI;
	float max = FA_TAnon_ -DBL_MAX;
	float min = FA_TAnon_ DBL_MAX;
	float nan = FA_TAnon_ NAN;
	float x = FA_TAnon_ sqrtf(5);
	x = FA_TAnon_ fabsf(5);
	x = FA_TAnon_ fmaxf(5, 45555);
	x = FA_TAnon_ fminf(5, 45555);
	x = FA_TAnon_ sinf(5);
	x = FA_TAnon_ cosf(5);
	x = FA_TAnon_ atan2f(5, 3);
	x = FA_TAnon_ tanf(5);
	x = FA_TAnon_ expf(5);
	x = FA_TAnon_ logf(5);
	x = FA_TAnon_ sqrtf(5);
	int xr = FA_TAnon_ roundf(5);
	xr = FA_TAnon_ floorf(5);
	xr = FA_TAnon_ ceilf(5);
	x = FA_TAnon_ atanf(5);
	x = FA_TAnon_ asinf(5);
	x = FA_TAnon_ acosf(5);
	x = FA_TAnon_ powf(5, 4);
	x = FA_TAnon_ rand() * 5;
	BOOL b = FA_TAnon_ isfinite(45454);
	b = FA_TAnon_ isnan(45454);
	float j = x + xr;
	j += x;
	float k = ( (b) ? -x : x);
}
- (void) testReflect{
	
	id_anon *obj = struct {
	a:@"aaaaa"
	} structName;
	BOOL b = [ReflectFA_TAnon_ hasField:obj field:@"a"];
	id f = [ReflectFA_TAnon_ field:obj field:@"a"];
	if (obj != nil) [objFA_TAnon_ -GFA2-__SetField-TDynamic-];
	[self.__SetField-TDynamic-];
	id p = (id)[self.__Field-TDynamic-];
	[ReflectFA_TAnon_ callMethod:self func:self.testStd args:[[NSMutableArray alloc] initWithObjects:, nil]]];
	[ReflectFA_TAnon_ callMethod:self func:self.callLotsOfArguments args:[[NSMutableArray alloc] initWithObjects:[NSNumber numberWithInt:1], [NSNumber numberWithInt:2], [NSNumber numberWithInt:3], [NSNumber numberWithInt:4], nil]]];
	
	NSMutableArray *fs = [ReflectFA_TAnon_ fields:obj];
	BOOL isf = [ReflectFA_TAnon_ isFunction:self.testStd];
	int i = [ReflectFA_TAnon_ compare:1 b:2];
	BOOL cm = [ReflectFA_TAnon_ compareMethods:self.testStd f2:self.testString];
	BOOL isobj = [ReflectFA_TAnon_ isObject:obj];
	isobj = [ReflectFA_TAnon_ isObject:self.testStd];
	[ReflectFA_TAnon_ deleteField:obj f:@"a"];
	
	id_anon *obj2 = [ReflectFA_TAnon_ copy:obj];
}
- (void) testStd{
	int _int = 3;
	BOOL _BOOL = [StdFA_TAnon_ is:self.d1 t:float];
	float _float = [StdFA_TAnon_ parseFloat:@"55454.65"];
	_int = [StdFA_TAnon_ parseInt:@"435345.23"];
	_int = [StdFA_TAnon_ random:543];
	
	NSMutableString *string = [StdFA_TAnon_ string:_int];
}
- (void) testString{
	
	NSMutableString *string = [[NSMutableString alloc] init:@"abcdefghijklmnopqrstuvwxyz"];
	int len = string.length;
	
	NSMutableString *s = [string  characterAtIndex:5];
	int ch = [string  characterAtIndex:5];
	int i = [string  rangeOfString:@"abc" startIndex:nil];
	int i1 = [string  rangeOfString:@"abc" startIndex:2];
	int li = [string  rangeOfString options:NSBackwardsSearch:@"abc" startIndex:nil];
	
	NSMutableArray *components = [string  componentsSeparatedByString:@"-"];
	
	NSMutableString *s2 = [string  substringWithRange:5 len:nil];
	s2 = [string  substringWithRange:5 len:len];
	s2 = [string  substringWithRange:5 endIndex:nil];
	s2 = [string  substringWithRange:1 endIndex:len];
	s2 = [string  lowercaseString];
	s2 = [string  uppercaseString];
	s2 = [string  description];
	
	NSMutableString *s3 = @"\t";
	
	StringBuf *buf = [[StringBuf alloc] init];
	[buf.b appendString:@"abc"];
	[buf.b appendString:@""];
	buf.b += [@"abcdefghijklmnopqerstuvwxyz"  substringWithRange:5 len:nil];
	buf.b += [@"abcdefghijklmnopqerstuvwxyz"  substringWithRange:5 len:10];
	
	NSMutableString *strbuf = buf.b;
	
	NSMutableString *st = [StringToolsFA_TAnon_ urlEncode:@"http://imagin.ro/Gorgeous Elena/2"];
	st = [StringToolsFA_TAnon_ urlDecode:@"http://imagin.ro/Gorgeous Elena/2"];
	st = [StringToolsFA_TAnon_ htmlEscape:@"<a href= &>" quotes:nil];
	st = [StringToolsFA_TAnon_ htmlUnescape:@"<a href= &>"];
	st = [StringToolsFA_TAnon_ ltrim:@" abcdefgh"];
	st = [StringToolsFA_TAnon_ rtrim:@"abcdefgh "];
	st = [StringToolsFA_TAnon_ trim:@" abcdefgh "];
	st = [StringToolsFA_TAnon_ rpad:@"abcdefgh" c:@"0" l:10];
	st = [StringToolsFA_TAnon_ lpad:@"abcdefgh" c:@"0" l:10];
	st = [StringToolsFA_TAnon_ replace:@"abcdefgh" sub:@"abc" by:@"_abc"];
	BOOL b = [StringToolsFA_TAnon_ startsWith:@"abcdefg" start:@"abc"];
	b = [StringToolsFA_TAnon_ endsWith:@"abcdefg" end:@"efg"];
	b = [StringToolsFA_TAnon_ isSpace:@"abcdefg" pos:3];
	
	NSMutableString *i2 = [StringToolsFA_TAnon_ hex:345345 digits:10];
	
	NSMutableString *sfin = [strbuf stringByAppendingString:st];
	sfin = [[strbuf stringByAppendingString:st] stringByAppendingString:s2];
	[sfin appendString:@"abc"];
	sfin = [[st stringByAppendingString:@"abc"] stringByAppendingString:@"5"];
	sfin = [@"55" stringByAppendingString:@"abc"];
}
- (void) testSys{
	[SysFA_TAnon_ print:@"hello world"];
	[SysFA_TAnon_ println:@"hello world"];
	
	NSMutableArray *arr = [SysFA_TAnon_ args];
	int _int = [SysFA_TAnon_ command:@"cd" args:[[NSMutableArray alloc] initWithObjects:@"~", nil]]];
	_int = [SysFA_TAnon_ command:@"ls" args:[[NSMutableArray alloc] initWithObjects:, nil]]];
	float _float = [SysFA_TAnon_ cpuTime];
	
	Hash *hash = [SysFA_TAnon_ environment];
	
	NSMutableString *string = [SysFA_TAnon_ executablePath];
	[SysFA_TAnon_ exit:0];
	_int = [SysFA_TAnon_ getChar:YES];
	string = [SysFA_TAnon_ getCwd];
	string = [SysFA_TAnon_ getEnv:@"VAR1"];
	[SysFA_TAnon_ putEnv:@"VAR1" v:@"val 1"];
	[SysFA_TAnon_ setCwd:@"thisdir"];
	BOOL bool = [SysFA_TAnon_ setTimeLocale:@"loc"];
	[SysFA_TAnon_ sleep:5.5];
	
	Output *_out = [SysFA_TAnon_ stderr];
	
	Input *_in = [SysFA_TAnon_ stdin];
	_out = [SysFA_TAnon_ stdout];
	string = [SysFA_TAnon_ systemName];
	_float = [SysFA_TAnon_ time];
}
- (void) testType{
	
	Class *sup = [TypeFA_TAnon_ getSuperClass:NSString];
	
	NSMutableString *sups = [TypeFA_TAnon_ getClassName:NSString];
	
	Class *cl = [TypeFA_TAnon_ resolveClass:@"ios.map.MKMapView"];
}
- (void) testXml{
}
- (void) testTimer{
	
	NSMutableArray *_g = [[NSMutableArray alloc] initWithObjects:self, nil]];
	
	Timer *timer = [[Timer alloc] init:50];
	timer.run = self.testXml;
	[timer stop];
	timer = [TimerFA_TAnon_ delay:self.testTimer time_ms:50];
	timer = [TimerFA_TAnon_ delay:^(void){
		[[_g objectAtIndex:0] testTimer];
	} time_ms:50];
	[TimerFA_TAnon_ measure:self.testTimer pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Tests.hx",@"519",@"Tests",@"testTimer",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	float f = [TimerFA_TAnon_ stamp];
}
- (void) testFrameworksImport{
}
- (int) getWidth{
	return 0;
}
- (int) setWidth:(int)v{
	return 0;
}
- (int) add:(int)a b:(int)b{
	return a + b;
}
- (int) minus:(int)a b:(int)b{
	return a - b;
}
- (void) callLotsOfArguments:(int)arg1 arg2:(int)arg2 arg3:(int)arg3 arg4:(int)arg4{
	[self.optionalArguments:0 arg2:1 arg3:2 arg4:nil];
	[self.optionalArguments1:0 arg2:1 arg3:2 arg4:nil];
	[self.optionalArguments2:0 arg2:nil arg3:nil arg4:3];
	[self.optionalArguments3:0 arg2:1 arg3:2 arg4:3];
}
- (void) optionalArguments:(int)arg1 arg2:(int)arg2 arg3:(int)arg3 arg4:(int)arg4{
	if (arg4==nil) arg4=nil;
}
- (void) optionalArguments1:(int)arg1 arg2:(int)arg2 arg3:(int)arg3 arg4:(int)arg4{
	if (arg4==nil) arg4=5;
}
- (void) optionalArguments2:(int)arg1 arg2:(int)arg2 arg3:(int)arg3 arg4:(int)arg4{
	if (arg3==nil) arg3=nil;
	if (arg2==nil) arg2=nil;
}
- (void) optionalArguments3:(int)arg1 arg2:(int)arg2 arg3:(int)arg3 arg4:(int)arg4{
	if (arg3==nil) arg3=nil;
	if (arg2==nil) arg2=6;
}
- (void) init{
	int x = 6;
	self.s = @"init";
}
- (void) printHello{
	[LogFA_TAnon_ trace:@"Hello from Haxe Objective-C" infos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"Tests.hx",@"570",@"Tests",@"printHello",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (id) init{
	self = [super init];
	self.s = @"str";
	self.d2 = 4.5;
	self.d1 = 34;
	return self;
}

@end

@implementation Tests2

@synthesize d1;
- (void) methodInTests2{
}
- (id) init{
	self = [super init];
	self.d1 = 34;
	
	NSMutableArray *arr = [[NSMutableArray alloc] initWithObjects:self.d1, self.d1, [NSNumber numberWithInt:50], nil]];
	return self;
}

@end
