//
//  Tests3
//  App name
//
//  Source generated by Haxe Objective-C target
//

#import "Tests3.h"

@implementation Tests3

@synthesize d1;
- (id) new{
	self = [super init];
	self.d1 = 34;
	return self;
}

@end
