//
//  Tests3
//  Tests
//
//  Source generated by Haxe Objective-C target
//

typedef enum{
	Red,
	Green,
	Blue
} Color;



@interface Tests3 : NSObject

@property (nonatomic) int d1;
- (id) init;

@end

