//
//  Tests3
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Tests3.h"

@implementation Tests3

@synthesize d1;
id(^block_init)() = ^() { [me init]; };
- (id) init{
	self = [super init];
	me = self;
	self.d1 = 34;
	return self;
}

@end
