//
//  Tests3
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "Tests3.h"

@implementation Tests3

@synthesize d1;
- (id) init{
	self = [super init];
	self.FA_ .d1 = 34;
	return self;
}

@end
