//
//  main.m
//  app_delegate_class
//
//  Source generated by Haxe Objective-C target
//



#import "Class.h"
#import "Reflect.h"
#import "Enum.h"
#import "EnumValue.h"
#import "Array.h"
#import "Type.h"
#import "ValueType.h"

@interface Type : NSObject

+ (Class*) getClass:(id)o;
+ (Enum*) getEnum:(EnumValue*)o;
+ (Class*) getSuperClass:(Class*)c;
+ (NSMutableString*) getClassName:(Class*)c;
+ (NSMutableString*) getEnumName:(Enum*)e;
+ (Class*) resolveClass:(NSMutableString*)name;
+ (Enum*) resolveEnum:(NSMutableString*)name;
+ (id) createInstance:(Class*)cl args:(NSMutabeArray*)args;
+ (id) createEmptyInstance:(Class*)cl;
+ (id) createEnum:(Enum*)e constr:(NSMutableString*)constr params:(NSMutabeArray*)params;
+ (id) createEnumIndex:(Enum*)e index:(int)index params:(NSMutabeArray*)params;
+ (NSMutabeArray*) getInstanceFields:(Class*)c;
+ (NSMutabeArray*) getClassFields:(Class*)c;
+ (NSMutabeArray*) getEnumConstructs:(Enum*)e;
+ (ValueType*) typeof:(id)v;
+ (BOOL) enumEq:(id)a b:(id)b;
+ (NSMutableString*) enumConstructor:(EnumValue*)e;
+ (NSMutabeArray*) enumParameters:(EnumValue*)e;
+ (int) enumIndex:(EnumValue*)e;
+ (NSMutabeArray*) allEnums:(Enum*)e;

@end
