//
//  TestInt64
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../haxe/Int64.h"
#import "../Std.h"
#import "../unit/Test.h"

@interface TestInt64 : Test 

- (void) test;
- (id) init;

@end

