//
//  TestXML
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/TestXML.h"

@implementation TestXML

- (void) checkExc:(Xml*)x pos:(id)pos{
	// Simulated optional arguments
	if (pos == nil) pos = nil;
	
	
	NSMutableArray *x1 = [[NSMutableArray alloc] initWithObjects:x, nil];
	[self exc:^- (void) {
		[[x1 objectAtIndex:0] get_nodeName];
	} pos:pos];
	[self exc:^- (void) {
		[[x1 objectAtIndex:0] get_nodeValue];
	} pos:pos];
	[self exc:^- (void) {
		[[x1 objectAtIndex:0] attributes];
	} pos:pos];
	[self exc:^- (void) {
		[[x1 objectAtIndex:0] get:(NSMutableString*)@"att"];
	} pos:pos];
	[self exc:^- (void) {
		[[x1 objectAtIndex:0] exists:(NSMutableString*)@"att"];
	} pos:pos];
}
- (void) testBasic{
	
	Xml *x = [Xml parse:(NSMutableString*)@"<a href=\"hello\">World<b/></a>"];
	[self t:binop[Xml compare-TDynamic-] pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"16",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:x nodeType v2:Xml Document pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"18",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self checkExc:x pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"19",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	x = [x firstChild];
	[self eq:x nodeType v2:Xml Element pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"22",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x get_nodeName] v2:(NSMutableString*)@"a" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"26",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[x set_nodeName:(NSMutableString*)@"b"];
	[self eq:[x get_nodeName] v2:(NSMutableString*)@"b" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"28",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x toString] v2:(NSMutableString*)@"<b href=\"hello\">World<b/></b>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"29",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x get:(NSMutableString*)@"href"] v2:(NSMutableString*)@"hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"32",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x get:(NSMutableString*)@"other"] v2:nil pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"33",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x exists:(NSMutableString*)@"href"] v2:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"34",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x exists:(NSMutableString*)@"other"] v2:NO pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"35",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Lambda array:struct {
	iterator:x attributes
	} structName] join:(NSMutableString*)@"#"] v2:(NSMutableString*)@"href" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"36",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[x remove:(NSMutableString*)@"href"];
	[self eq:[[Lambda array:struct {
	iterator:x attributes
	} structName] join:(NSMutableString*)@"#"] v2:(NSMutableString*)@"" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"38",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x toString] v2:(NSMutableString*)@"<b>World<b/></b>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"39",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[x firstChild] get_nodeValue] v2:(NSMutableString*)@"World" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"42",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[x firstElement] get_nodeName] v2:(NSMutableString*)@"b" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"43",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self exc:^- (void) {
		[Xml parse:(NSMutableString*)@"<node>"];
	} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"46",@"unit.TestXML",@"testBasic",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testFormat{
	[self eq:[[Xml parse:(NSMutableString*)@"<a><b><c/> <d/> \n <e/><![CDATA[<x>]]></b></a>"] toString] v2:(NSMutableString*)@"<a><b><c/> <d/> \n <e/><![CDATA[<x>]]></b></a>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"54",@"unit.TestXML",@"testFormat",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml parse:(NSMutableString*)@"\""] toString] v2:(NSMutableString*)@"\"" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"59",@"unit.TestXML",@"testFormat",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testComplex{
	
	NSMutableString *header = (NSMutableString*)@"<?some header?>";
	
	NSMutableString *doctype = (NSMutableString*)@"<!DOCTYPE root SYSTEM \"\">";
	
	NSMutableString *comment = (NSMutableString*)@"<!--Comment-->";
	
	NSMutableString *xml = (NSMutableString*)@"<html><body><![CDATA[<a href=\"CDATA\"/>&lt;]]></body></html>";
	
	Xml *x = [Xml parse:[[[header stringByAppendingString:doctype] stringByAppendingString:comment] stringByAppendingString:xml]];
	[self eq:[x toString] v2:[[[header stringByAppendingString:doctype] stringByAppendingString:comment] stringByAppendingString:xml] pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"87",@"unit.TestXML",@"testComplex",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testWhitespaces{
	
	Xml *x = [Xml parse:(NSMutableString*)@"<a> </a><b></b> \n <c/>"];
	
	NSMutableArray *childs = (NSMutableArray*)[Lambda array:x];
	[self eq:childs length v2:4 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"96",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	Xml *d = [childs objectAtIndex:2];
	[self eq:d nodeType v2:Xml PCData pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"99",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[d get_nodeValue] v2:(NSMutableString*)@" \n " pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"100",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	id el = [x elements];
	
	Xml *a = [el next];
	[self eq:[[a firstChild] get_nodeValue] v2:(NSMutableString*)@" " pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"104",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	Xml *b = [el next];
	[self eq:[[b firstChild] get_nodeValue] v2:(NSMutableString*)@"" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"110",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[[x toString] componentsSeparatedByString:(NSMutableString*)@"\n"] join:(NSMutableString*)@"\\n"] v2:(NSMutableString*)@"<a> </a><b></b> \\n <c/>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"111",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	Xml *c = [el next];
	[self eq:[c firstChild] v2:nil pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"114",@"unit.TestXML",@"testWhitespaces",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testCreate{
	[self eq:[[Xml createDocument] toString] v2:(NSMutableString*)@"" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"118",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml createPCData:(NSMutableString*)@"Hello"] toString] v2:(NSMutableString*)@"Hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"119",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml createCData:(NSMutableString*)@"<x>"] toString] v2:(NSMutableString*)@"<![CDATA[<x>]]>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"125",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml createComment:(NSMutableString*)@"Hello"] toString] v2:(NSMutableString*)@"<!--Hello-->" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"126",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml createProcessingInstruction:(NSMutableString*)@"XHTML"] toString] v2:(NSMutableString*)@"<?XHTML?>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"133",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml createDocType:(NSMutableString*)@"XHTML"] toString] v2:(NSMutableString*)@"<!DOCTYPE XHTML>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"134",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[[Xml parse:(NSMutableString*)@"<!--Hello-->"] firstChild] get_nodeValue] v2:(NSMutableString*)@"Hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"137",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	Xml *c = [Xml createComment:(NSMutableString*)@"Hello"];
	[self eq:[c get_nodeValue] v2:(NSMutableString*)@"Hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"139",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[c set_nodeValue:(NSMutableString*)@"Blabla"];
	[self eq:[c get_nodeValue] v2:(NSMutableString*)@"Blabla" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"141",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[c toString] v2:(NSMutableString*)@"<!--Blabla-->" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"142",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[[Xml parse:(NSMutableString*)@"<![CDATA[Hello]]>"] firstChild] get_nodeValue] v2:(NSMutableString*)@"Hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"143",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	Xml *c1 = [Xml createCData:(NSMutableString*)@"Hello"];
	[self eq:[c1 get_nodeValue] v2:(NSMutableString*)@"Hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"145",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[c1 set_nodeValue:(NSMutableString*)@"Blabla"];
	[self eq:[c1 get_nodeValue] v2:(NSMutableString*)@"Blabla" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"147",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[c1 toString] v2:(NSMutableString*)@"<![CDATA[Blabla]]>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"148",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[[Xml createPCData:(NSMutableString*)@"Hello"] get_nodeValue] v2:(NSMutableString*)@"Hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"149",@"unit.TestXML",@"testCreate",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testNS{
	
	Xml *x = [[Xml parse:(NSMutableString*)@"<xhtml:br xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" xhtml:alt=\"test\"><hello/></xhtml:br>"] firstChild];
	[self eq:x nodeType v2:Xml Element pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"154",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x get_nodeName] v2:(NSMutableString*)@"xhtml:br" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"155",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:[x exists:(NSMutableString*)@"xhtml:alt"] pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"156",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x get:(NSMutableString*)@"xhtml:alt"] v2:(NSMutableString*)@"test" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"157",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[x get:(NSMutableString*)@"xhtml:other"] v2:nil pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"158",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[x set:(NSMutableString*)@"xhtml:alt" value:(NSMutableString*)@"bye"];
	[self eq:[x get:(NSMutableString*)@"xhtml:alt"] v2:(NSMutableString*)@"bye" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"160",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	
	Xml *h = [x firstElement];
	[self eq:[h get_nodeName] v2:(NSMutableString*)@"hello" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"163",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[h set_nodeName:(NSMutableString*)@"em"];
	[self eq:[h get_nodeName] v2:(NSMutableString*)@"em" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"165",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[Lambda count:struct {
	iterator:((SEL)($this:(snd ctx.path)) 
	NSMutableArray *f = [[NSMutableArray alloc] initWithObjects:x elementsNamed, nil]
	__r__ = ^- (id) {
		return [[f objectAtIndex:0]:(NSMutableString*)@"em"];
	}
	return __r__{
		
		SEL* __r__}
	}(self))
	} structName pred:nil] v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"167",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[h set_nodeName:(NSMutableString*)@"xhtml:em"];
	[self eq:[Lambda count:struct {
	iterator:((SEL)($this:(snd ctx.path)) 
	NSMutableArray *f = [[NSMutableArray alloc] initWithObjects:x elementsNamed, nil]
	__r__2 = ^- (id) {
		return [[f objectAtIndex:0]:(NSMutableString*)@"xhtml:em"];
	}
	return __r__2{
		
		SEL* __r__2}
	}(self))
	} structName pred:nil] v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"171",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[Lambda count:struct {
	iterator:((SEL)($this:(snd ctx.path)) 
	NSMutableArray *f = [[NSMutableArray alloc] initWithObjects:x elementsNamed, nil]
	__r__3 = ^- (id) {
		return [[f objectAtIndex:0]:(NSMutableString*)@"em"];
	}
	return __r__3{
		
		SEL* __r__3}
	}(self))
	} structName pred:nil] v2:0 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"172",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[h get_nodeName] v2:(NSMutableString*)@"xhtml:em" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"174",@"unit.TestXML",@"testNS",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testNodetype{
	
	NSMutableArray *element = [[NSMutableArray alloc] initWithObjects:[Xml createElement:(NSMutableString*)@"x"], nil];
	
	NSMutableArray *l = [[NSMutableArray alloc] initWithObjects:[Xml createPCData:(NSMutableString*)@"x"], [Xml createCData:(NSMutableString*)@"x"], [Xml createDocType:(NSMutableString*)@"x"], [Xml createProcessingInstruction:(NSMutableString*)@"x"], [Xml createComment:(NSMutableString*)@"x"], nil];
	{
		int _g = 0;
		while (_g < l.length) {
			
			NSMutableArray *xml = [[NSMutableArray alloc] initWithObjects:[l objectAtIndex:_g], nil];
			++_g;
			[self exc:^- (void) {
				[[xml objectAtIndex:0] firstChild];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"183",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				[[xml objectAtIndex:0] firstElement];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"184",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				[[xml objectAtIndex:0] elements];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"185",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				[[xml objectAtIndex:0] elementsNamed:(NSMutableString*)@"x"];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"186",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				[[xml objectAtIndex:0] addChild:[element objectAtIndex:0]];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"187",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				[[xml objectAtIndex:0] removeChild:[element objectAtIndex:0]];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"188",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				[[xml objectAtIndex:0] insertChild:[element objectAtIndex:0] pos:0];
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"189",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
			[self exc:^- (void) {
				{
					id _it = [[xml objectAtIndex:0] iterator];
					while ( [_it hasNext] ) do {
						Xml x = [_it next];
						nil;
					}
				}
			} pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"190",@"unit.TestXML",@"testNodetype",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
		}
	}
}
- (void) testEntities{
	
	NSMutableArray *entities = [[NSMutableArray alloc] initWithObjects:(NSMutableString*)@"&lt;", (NSMutableString*)@"&gt;", (NSMutableString*)@"&quot;", (NSMutableString*)@"&amp;", (NSMutableString*)@"&apos;", (NSMutableString*)@"&nbsp;", (NSMutableString*)@"&euro;", (NSMutableString*)@"&#64;", (NSMutableString*)@"&#244;", (NSMutableString*)@"&#x3F;", (NSMutableString*)@"&#xFF;", nil];
	
	NSMutableArray *values = (NSMutableArray*)[entities copy];
	{
		int _g1 = 0; int _g = entities.length;
		while (_g1 < _g) {
			int i = _g1++;
			[self infos:[entities objectAtIndex:i]];
			[self eq:[[[Xml parse:[entities objectAtIndex:i]] firstChild] get_nodeValue] v2:[values objectAtIndex:i] pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"217",@"unit.TestXML",@"testEntities",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
		}
	}
}
- (void) testCustomXmlParser{
	
	NSMutableArray *entities = [[NSMutableArray alloc] initWithObjects:(NSMutableString*)@"&lt;", (NSMutableString*)@"&gt;", (NSMutableString*)@"&quot;", (NSMutableString*)@"&amp;", (NSMutableString*)@"&apos;", (NSMutableString*)@"&euro;", (NSMutableString*)@"&#64;", (NSMutableString*)@"&#244;", (NSMutableString*)@"&#x3F;", (NSMutableString*)@"&#xFF;", nil];
	
	NSMutableArray *values = [[NSMutableArray alloc] initWithObjects:(NSMutableString*)@"<", (NSMutableString*)@">", (NSMutableString*)@"\"", (NSMutableString*)@"&", (NSMutableString*)@"'", (NSMutableString*)@"&euro;", (NSMutableString*)@"@", [NSMutableString fromCharCode:[NSNumber numberWithInt:244]], (NSMutableString*)@"?", [NSMutableString fromCharCode:[NSNumber numberWithInt:255]], nil];
	{
		int _g1 = 0; int _g = entities.length;
		while (_g1 < _g) {
			int i = _g1++;
			[self infos:[entities objectAtIndex:i]];
			[self eq:[[[Parser parse:[entities objectAtIndex:i]] firstChild] get_nodeValue] v2:[values objectAtIndex:i] pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"227",@"unit.TestXML",@"testCustomXmlParser",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
		}
	}
	
	NSMutableString *s = (NSMutableString*)@"<a>&gt;<b>&lt;</b>&lt;&gt;<b>&gt;&lt;</b>\"</a>";
	
	Xml *xml = [Parser parse:s];
	[self eq:s v2:[xml toString] pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"232",@"unit.TestXML",@"testCustomXmlParser",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (void) testMore{
	
	Xml *doc = [Xml parse:(NSMutableString*)@"<a>A</a><i>I</i>"];
	
	Xml *aElement = [[doc elementsNamed:(NSMutableString*)@"a"] next];
	
	Xml *iElement = [[doc elementsNamed:(NSMutableString*)@"i"] next];
	[iElement addChild:aElement];
	[self eq:[doc toString] v2:(NSMutableString*)@"<i>I<a>A</a></i>" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestXML.hx",@"241",@"unit.TestXML",@"testMore",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (id) init{
	self = [super init];
	[super];
	return self;
}

@end
