//
//  TestMisc
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../unit/MyDynamicClass.h"

@interface MyDynamicClass : HXObject

+ (int) Z:(int)val;
// Defining a dynamic method
+ (int) staticDynamic:(int)x y:(int)y;
@property (nonatomic,copy) int(^property_staticDynamic)(int, int);
+ (int) W:(int)val;
+ (int) get_W;
+ (int) set_W:(int)v;
@property (nonatomic) int v;
- (int) get;
// Defining a dynamic method
- (int) add:(int)x y:(int)y;
@property (nonatomic,copy) int(^property_add)(int, int);
- (int) iadd:(int)x y:(int)y;
- (id) init:(int)v;

@end



#import "../unit/MyDynamicClass.h"

@interface MyDynamicSubClass : MyDynamicClass 

// Defining a dynamic method
- (int) add:(int)x y:(int)y;
@property (nonatomic,copy) int(^property_add)(int, int);
- (id) init:(int)v;

@end



#import "../unit/MyDynamicClass.h"

@interface MyDynamicSubClass2 : MyDynamicClass 

// Defining a dynamic method
- (int) add:(int)x y:(int)y;
@property (nonatomic,copy) int(^property_add)(int, int);
- (id) init:(int)v;

@end



#import "../unit/MyDynamicClass.h"

@interface MyOtherDynamicClass : MyDynamicClass 

- (id) init:(int)v;

@end




@interface IDefArgs : HXObject



@end




@interface BaseDefArgs : HXObject

- (int) get:(int)x;

@end



#import "../unit/BaseDefArgs.h"

@interface ExtDefArgs : BaseDefArgs <IDefArgs>

- (int) get:(int)x;
- (id) init;

@end



#import "../String.h"

@interface BaseConstrOpt : HXObject

@property (nonatomic, strong) NSMutableString *s;
@property (nonatomic) int i;
@property (nonatomic) BOOL b;
- (id) init:(NSMutableString*)s i:(int)i b:(BOOL)b;

@end



#import "../unit/BaseConstrOpt.h"

@interface SubConstrOpt : BaseConstrOpt 

- (id) init;

@end



#import "../String.h"
#import "../unit/BaseConstrOpt.h"

@interface SubConstrOpt2 : BaseConstrOpt 

- (id) init:(NSMutableString*)s i:(int)i b:(BOOL)b;

@end



#import "../String.h"
#import "../unit/BaseConstrOpt.h"

@interface SubConstrOpt3 : BaseConstrOpt 

- (id) init:(NSMutableString*)s i:(int)i;

@end



#import "../String.h"
#import "../unit/TestMisc.h"
#import "../Date.h"
#import "../unit/MyClass.h"
#import "../Array.h"
#import "../Math.h"
#import "../unit/MyEnum.h"
#import "../Type.h"
#import "../haxe/crypto/Md5.h"
#import "../unit/MyDynamicClass.h"
#import "../unit/MyDynamicSubClass.h"
#import "../unit/MyOtherDynamicClass.h"
#import "../haxe/io/Bytes.h"
#import "../haxe/crypto/Sha1.h"
#import "../haxe/crypto/BaseCode.h"
#import "../StringTools.h"
#import "../unit/ExtDefArgs.h"
#import "../StringBuf.h"
#import "../Std.h"
#import "../haxe/Json.h"
#import "../unit/BaseConstrOpt.h"
#import "../unit/SubConstrOpt.h"
#import "../unit/SubConstrOpt2.h"
#import "../unit/SubConstrOpt3.h"
#import "../unit/Test.h"

@interface TestMisc : Test 

+ (NSMutableString*) unit:(NSMutableString*)val;
+ (int) foo:(int)x;

- (void) testPackageConflict;
- (void) testDate;
- (void) testClosure;
- (void) testCaptureUnique;
- (void) testCaptureUnique2;
- (void) testSelfRef;
- (void) testHiddenType;
- (void) testHiddenTypeScope;
- (void) testHiddenTypeCapture;
- (int) id:(int)x;
- (int) sq:(int)x;
- (void) testPropertyInit;
- (void) testInlineClosure;
- (void) testDynamicClosure;
- (void) testMD5;
- (void) testSHA1;
- (void) testBaseCode;
- (void) testUrlEncode;
- (id) opt1:(int)x y:(NSMutableString*)y;
- (id) opt2:(int)x y:(NSMutableString*)y;
- (id) opt3:(int)x y:(float)y;
- (int) opt4:(int)x;
- (void) testOptionalParams;
- (void) testIncr;
- (void) testInitOrder;
- (void) testInline;
- (void) testEvalAccessOrder;
- (void) testStaticVarFun;
- (void) testDefArgs;
- (void) testStringBuf;
- (void) testToString;
- (void) testFormat;
- (void) testJSon;
- (void) testConstructorsOpts;
- (id) init;

@end

