//
//  TestSpecification
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../String.h"
#import "../unit/C.h"

@interface C : NSObject

+ (void) staticFunc;
+ (NSMutableString*) staticVar:(NSMutableString*)val;
+ (NSMutableString*) staticProp:(NSMutableString*)val;
- (void) func;
@property (nonatomic, strong) NSMutableString *v;
@property (nonatomic, strong) NSMutableString *prop;
- (id) init;

@end



#import "../unit/C.h"

@interface CChild : C 

- (id) init;

@end



#import "../unit/C.h"

@interface CDyn : C 

- (id) init;

@end




@interface EmptyClass : NSObject

- (id) init;

@end



#import "../String.h"

@interface ClassWithToString : NSObject

- (NSMutableString*) toString;
- (id) init;

@end



#import "../unit/_TestSpecification/ClassWithToString.h"

@interface ClassWithToStringChild : ClassWithToString 

- (id) init;

@end



#import "../String.h"
#import "../unit/_TestSpecification/ClassWithToString.h"

@interface ClassWithToStringChild2 : ClassWithToString 

- (NSMutableString*) toString;
- (id) init;

@end



#import "../String.h"

@interface ClassWithCtorDefaultValues : NSObject

@property (nonatomic) int a;
@property (nonatomic, strong) NSMutableString *b;
- (id) init:(int)a b:(NSMutableString*)b;

@end



#import "../String.h"
#import "../unit/_TestSpecification/ClassWithCtorDefaultValues.h"

@interface ClassWithCtorDefaultValuesChild : ClassWithCtorDefaultValues 

- (id) init:(int)a b:(NSMutableString*)b;

@end

typedef enum{
	NoArguments,
	OneArgument
} SomeEnum;


#import "../unit/TestSpecification.h"

@interface IntWrap : NSObject

+ (int) compare:(IntWrap*)a b:(IntWrap*)b;
@property (nonatomic) int i;
- (id) init:(int)i;

@end

typedef enum{
	NoArgs,
	OneArg,
	RecArg,
	MultipleArgs
} E;
typedef enum{
	EA,
	EB,
	EC
} EnumFlagTest;


#import "../unit/Test.h"

@interface TestSpecification : Test 

- (id) init;

@end

