//
//  TestOps
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/TestOps.h"

@implementation TestOps

- (void) testOps{
	[self eq:[@"3" stringByAppendingString:(NSMutableString*)@""] v2:(NSMutableString*)@"3" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"7",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[@"3" stringByAppendingString:(NSMutableString*)@""] v2:(NSMutableString*)@"3" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"8",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 +  ([@"2" stringByAppendingString:(NSMutableString*)@""]) v2:(NSMutableString*)@"12" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"9",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[@"1" stringByAppendingString:(NSMutableString*)@""] v2:(NSMutableString*)@"1" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"11",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[@"1" stringByAppendingString:(NSMutableString*)@""] v2:(NSMutableString*)@"1" pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"12",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"15",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"16",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"17",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"19",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"20",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:0 v2:0 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"21",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:-4 v2:-4 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"23",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:-6 v2:-6 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"24",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"26",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"27",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"28",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"29",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 % 3 * 4 v2:8 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"31",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 % 3 * 4 v2:8 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"32",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 % 12 v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"33",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5. v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"35",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5. v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"36",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:20. v2:20 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"37",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:8 v2:8 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"39",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:8 v2:8 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"40",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:4 v2:4 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"41",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self f:NO pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"43",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self f:NO pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"44",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self f:NO pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"45",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self f:NO pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"46",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 *  (10 % 3) v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"48",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 *  (10 % 3) v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"49",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:50 % 3 v2:2 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"50",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:10 % 3 * 5 v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"52",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:10 % 3 * 5 v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"53",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:10 % 15 v2:10 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"54",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:100 % 100 v2:0 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"55",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:-100 % 100 v2:0 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"56",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:101.5 % 100 v2:1.5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"57",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:-101.5 % 100 v2:-1.5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"58",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	float x = 101.5;
	x %= 100;
	[self eq:x v2:1.5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"61",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:isnan(5.0 % 0.0) pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"62",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:isnan(x %= 0.0) pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"63",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	id x1 = [[NSMutableArray alloc] initWithObjects:[NSNumber numberWithFloat:-101.5], nil];
	[x1 objectAtIndex:0] %= 100;
	[self eq:[x1 objectAtIndex:0] v2:-1.5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"71",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"72",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:30 v2:30 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"73",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"74",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:30 v2:30 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"75",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:2 v2:2 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"77",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:5 v2:5 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"78",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"80",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"81",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	BOOL k = NO;
	[self f:k = NO pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"84",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self f:k pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"85",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self f:( (k = YES) ? NO : YES) pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"86",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:k pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"87",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self t:YES pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"89",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	int x2 = 1;
	[self eq:-x2++ v2:-1 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"92",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:-x2-- v2:-2 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"93",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:[ ([(NSMutableString*)@"bla" stringByAppendingString:(NSMutableString*)@"x"]) indexOf:(NSMutableString*)@"x" startIndex:nil] v2:3 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"95",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:19 v2:19 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"97",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
	[self eq:19 v2:19 pos:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:@"TestOps.hx",@"98",@"unit.TestOps",@"testOps",nil] forKeys:[NSArray arrayWithObjects:@"fileName",@"lineNumber",@"className",@"methodName",nil]]];
}
- (id) init{
	self = [super init];
	[super];
	return self;
}

@end
