//
//  TestReflect
//  Test
//
//  Source generated by Haxe Objective-C target
//




@interface InterfWithProp : NSObject

@property (nonatomic) int x;

@end



#import "../unit/ClassWithProp.h"

@interface ClassWithProp : NSObject<InterfWithProp>

+ (int) STAT_X:(int)val;
+ (int) set_STAT_X:(int)v;
@property (nonatomic, getter=get_x, setter=set_x) int x;
@property (nonatomic) int _x;
- (int) get_x;
- (int) set_x:(int)v;
- (id) init;

@end



#import "../unit/ClassWithProp.h"

@interface SubClassWithProp : ClassWithProp 

@property (nonatomic, setter=set_y) int y;
- (int) get_x;
- (int) get_y;
- (int) set_y:(int)v;
- (id) init;

@end



#import "../Array.h"
#import "../String.h"
#import "../haxe/ds/StringMap.h"
#import "../List.h"
#import "../Date.h"
#import "../Xml.h"
#import "../Math.h"
#import "../unit/MyEnum.h"
#import "../unit/MyClass.h"
#import "../unit/MySubClass.h"
#import "../Class.h"
#import "../Enum.h"
#import "../unit/MyInterface.h"
#import "../unit/TestReflect.h"
#import "../Type.h"
#import "../Std.h"
#import "../ValueType.h"
#import "../Reflect.h"
#import "../unit/ClassWithProp.h"
#import "../unit/SubClassWithProp.h"
#import "../unit/Test.h"

@interface TestReflect : Test 

+ (NSMutableArray*) TYPES:(NSMutableArray*)val;
+ (NSMutableString*) u:(NSMutableString*)s;
+ (NSMutableString*) u2:(NSMutableString*)s s2:(NSMutableString*)s2;
+ (NSMutableArray*) TNAMES:(NSMutableArray*)val;
- (void) testTypes;
- (void) testIs;
- (void) is:(id)v t1:(id)t1 t2:(id)t2 pos:(id)pos;
- (void) testTypeof;
- (void) typeof:(id)v rt:(Type*)rt pos:(id)pos;
- (void) testConv;
- (void) testCreate;
- (void) testCompare;
- (void) testGetProp;
- (id) init;

@end

